/* MAP MODES */
export const MAP_MODE = {
  VIEW: 'VIEW',
  ADD_ROUTE: 'ADD_ROUTE',
}

/* DEBOUNCE ACTIONS */
export const DEBOUNCE_ACTIONS = {
  GET_PLACES: 'GET_PLACES',
  GET_PATH: 'GET_PATH',
}

/* STATES IN ADDING A ROUTE */
export const ADD_ROUTE = {
  SETTING_ORIGIN: 'SETTING_ORIGIN',
  ADDING_POINTS: 'ADDING_POINTS',
}
